image:
  frontend:
    repository: myaccount.dkr.ecr.us-east-1.amazonaws.com/novatriage-frontend
    tag: latest
    pullPolicy: Always
  api:
    repository: myaccount.dkr.ecr.us-east-1.amazonaws.com/novatriage-api
    tag: latest
    pullPolicy: Always

replicaCount: 2

ingress:
  enabled: true
  className: "nginx"
  host: "novatriage.example.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

env:
  AWS_REGION: us-east-1
  BEDROCK_NOVA_LITE_MODEL: us.amazon.nova-lite-v1:0
  BEDROCK_NOVA_PRO_MODEL: us.amazon.nova-pro-v1:0
  BEDROCK_NOVA_SONIC_MODEL: amazon.nova-2-sonic-v1:0
  APP_LANGUAGE_DEFAULT: en
  APP_PROTOCOL_DEFAULT: generic

secrets:
  existingSecretName: novatriage-secrets
